import './globals.css'
import 'react-toastify/ReactToastify.min.css'
import type { Metadata } from 'next'
import { Tauri } from 'next/font/google'

const tauri = Tauri({ subsets: ['latin'], weight: "400"})

export const metadata: Metadata = {
  title: 'Image Lite App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={tauri.className}>{children}
        
      </body>
    </html>
  )
}
